[build]
  base    = "f1-telemetry-app/frontend"
  command = "npm run build"
  publish = "f1-telemetry-app/frontend/dist"

[build.environment]
  VITE_DATA_CDN_URL = "https://cdn.jsdelivr.net/gh/undercutacademy/f1-data@master"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
